version: '3'

services:
  api:
    extends:
      file: docker-compose.common.yml
      service: mirria
    environment:
      - APP_COMPONENT=api
    ports:
      - 7788:3000
  crawler:
    extends:
      file: docker-compose.common.yml
      service: mirria
    environment:
      - APP_COMPONENT=crawler